![alt text](GL_Logo.png "Title")

# Math for Data Science (400)
## TA Session 1 - Week 2   ||   Date - 01 July 2022
### Gowtham S


In [21]:
import numpy as np
from numpy.linalg import linalg, inv

# Conversion of array to matrix


In [22]:
a= ([1, 2, 3], [3, 4, 5], [6,7,8])
mat = np.matrix(a)
print(a)
print(mat)

([1, 2, 3], [3, 4, 5], [6, 7, 8])
[[1 2 3]
 [3 4 5]
 [6 7 8]]


# Matrix Determinant

It is given by numpy.linalg.det() 

In [29]:
def mat_det(a):
    array = np.array(a)
    det = np.linalg.det(array)
    return det 

In [32]:
a = [[50, 29], [30, 44]]

In [33]:
print(mat_det(a))

1330.0000000000002


# Inverse of Matrix
It is given by numpy.linalg.inv(a)

In [45]:
def mat_inv(a):
    array = np.array(a)
    det = np.linalg.inv(array)
    return det 

In [48]:
a = [[1,2,3], [4,1,0], [0,0,1]]

In [49]:
print(mat_inv(a))

[[-0.14285714  0.28571429  0.42857143]
 [ 0.57142857 -0.14285714 -1.71428571]
 [ 0.          0.          1.        ]]


# Solving of Linear eqns in Matrix form
It is given by linalg.solve(lhs, rhs)

In [14]:
def linr_eqn(lhs,rhs):
    #a = np.array(lhs)
    #b = np.array(rhs)
    var = linalg.solve(lhs, rhs)
    return(var)

In [15]:
lhs = [[3, 4, 6], [2, 0, 5], [1, -8, 4]]
rhs = [[45], [-20], [35]]

In [16]:
print(linr_eqn(lhs,rhs))

[[ 315.]
 [ -30.]
 [-130.]]


# Matrix multiplication
It is given by np.dot(a, b)

In [10]:
def mat_mul(a,b):
    mul = np.dot(a, b)
    return (mul)

In [11]:
print(mat_mul(lhs, rhs))

[[265]
 [265]
 [345]]


# For all other Matrix operations refer
https://www.guru99.com/python-matrix.html

# Solving linear eqns

In [17]:
import sympy as sym
# Use sympy package to display the equation
sym.init_printing()
#sym.solve()
x,y,z = sym.symbols('x,y,z')

solns = sym.solve([
    1*x + 2*y - 16*z - 30, 
    3*x - 4*y - 14*z + 25,
    2*x - 10*y + 5*z + 20],
    [x, y, z])
print(f"{solns[x]}")
print(f"{solns[y]}")
print(f"{solns[z]}")

-3355/53
-1535/106
-405/53


# Cramer Rule

In [34]:
lhs = [[1, 2, 5], [9, 5, 10], [17, 8, 2]]
rhs = [1, 2, 3]
a= [[1, 2, 3], [3, 4, 5], [6,7,8]]

In [42]:
def cramer(lhs, rhs):

    # calculating the determinant for the above matrix

    d = np.linalg.det(lhs)
    print(d)
    var1 = [[rhs[0], rhs[1], rhs[2]], 
            [lhs[1][0], lhs[1][1], lhs[1][2]],
            [lhs[2][0], lhs[2][1], lhs[2][2]]]
    print(var1)
    var2 = [[lhs[0][0], lhs[0][1], lhs[0][2]], 
            [rhs[0], rhs[1], rhs[2]],
            [lhs[2][0], lhs[2][1], lhs[2][2]]]
    print(var2)
    var3 = [[lhs[0][0], lhs[0][1], lhs[0][2]], 
            [lhs[1][0], lhs[1][1], lhs[1][2]],
            [rhs[0], rhs[1], rhs[2]]]
    print(var3)

    d1 = np.linalg.det(var1)
    print(d1)
    d2 = np.linalg.det(var2)
    print(d2)
    d3 = np.linalg.det(var3)
    print(d3)

    # Case 1: When d!=0
    if d != 0:
        x = d1 / d
        y = d2 / d
        z = d3 / d

        print('x:', x, 'y:', y, 'z:', z)

    # Case 2: When d=0
    else:
        if (d1 != 0 or d2 != 0 or d3 !=0):
            print('No Solution')

        elif (d1 == 0 and d2 == 0 and d3 ==0):
            print('Infinetly Many Solutions')


    

In [43]:
cramer(a, rhs)

-3.7007434154172e-17
[[1, 2, 3], [3, 4, 5], [6, 7, 8]]
[[1, 2, 3], [1, 2, 3], [6, 7, 8]]
[[1, 2, 3], [3, 4, 5], [1, 2, 3]]
-3.7007434154172e-17
0.0
0.0
x: 1.0 y: -0.0 z: -0.0
