In [7]:
from scipy import stats
import sympy as sym

#problem a
x = [10,50,100,500,1000,5000]
y = [346.8,374,408,680,1020,3740]

slope, intercept, r_value, p_value, std_err = stats.linregress(x,y)

print("Average Rate of Change = ", round(slope, 2))
print("Vertical Intercept = ", round(intercept, 2))


#problem b
sym.init_printing()
x,y = sym.symbols('x,y')
f = sym.Eq(y,round(slope,2)*x+round(intercept,2))
print("Linear function",f)

predict_450 = 450 * slope + intercept
print("Gustavo will be paid if he sells 450 frozen bananas", round(predict_450, 2))


predict_n = 727.6
n = (predict_n - intercept)/slope
print("the number of frozen bananas sold if Gustavo's pay is $727.60", round(n))



Average Rate of Change =  0.68
Vertical Intercept =  340.0
Linear function Eq(y, 0.68*x + 340.0)
Gustavo will be paid if he sells 450 frozen bananas 646.0
the number of frozen bananas sold if Gustavo's pay is $727.60 570


In [11]:
int(596.07)

In [22]:
from scipy import stats
import sympy as sym


x = [0,1,2,3,4,5,6,7]
y = [0,42,88,109,121,150,203,215]

slope, intercept, r_value, p_value, std_err = stats.linregress(x,y)

#problem a
sym.init_printing()
x,y = sym.symbols('x,y')
f = sym.Eq(y,round(slope,2)*x+round(intercept,2))
print("Linear function",f)

#problem b
print("Predicted increase in miles driven per hour = ", round(slope, 2))
print("Predicted number of miles driven at the beginning = ", round(intercept, 2))

#problem c
print("correlation coefficient = ",round(r_value,4))
print("Hours worked and miles driven have a strong positive correlation")

#problem d

predict_10 = 10 * round(slope,2) + round(intercept,2)
print("the driver would have traveled distance in miles after 10 hours = ", round(predict_10, 2))



Linear function Eq(y, 29.86*x + 11.5)
Predicted increase in miles driven per hour =  29.86
Predicted number of miles driven at the beginning =  11.5
correlation coefficient =  0.9885
Hours worked and miles driven have a strong positive correlation
the driver would have traveled distance in miles after 10 hours =  310.1


In [27]:
import sympy as sym

x,y,z = sym.symbols('x,y,z')

solns = sym.solve([
    1*x + 1*y + 1*z - 183, 
    14*x + 19*y + 24*z - 3727,
    13*x + 20*y + 36*z - 4784],
    [x, y, z])

print(f'{round(solns[x])}')
print(f'{round(solns[y])}')
print(f'{round(solns[z])}')

36
61
86


In [33]:
import numpy as np
from numpy.linalg import linalg, inv
import sympy as sym
sym.init_printing()

def cramer(lhs,rhs):
    d = round(np.linalg.det(lhs))
    print(d)
    m = [[lhs[0][0],lhs[0][1],lhs[0][2]],
         [lhs[1][0],lhs[1][1],lhs[1][2]],
         [lhs[2][0],lhs[2][1],lhs[2][2]]]
    print(np.linalg.det(m))
    
    m1 = [[rhs[0],lhs[0][1],lhs[0][2]],
          [rhs[1],lhs[1][1],lhs[1][2]],
          [rhs[2],lhs[2][1],lhs[2][2]]] 
    print(m1)
          
    m2 = [[lhs[0][0],rhs[0],lhs[0][2]],
          [lhs[1][0],rhs[1],lhs[1][2]],
          [lhs[2][0],rhs[2],lhs[2][2]]] 
    print(m2)
          
    m3 = [[lhs[0][0],lhs[0][1],rhs[0]],
          [lhs[1][0],lhs[1][1],rhs[1]],
          [lhs[2][0],lhs[2][1],rhs[2]]] 
    print(m3)

    d1 = round(np.linalg.det(m1))
    print(d1)
    d2 = round(np.linalg.det(m2))
    print(d2)
    d3 = round(np.linalg.det(m3))
    print(d3)
           
    if d!= 0:
           x = d1/d
           y = d2/d
           z = d3/d
           print('x: ',round(x),'y: ',round(y),'z: ',round(z))
    else:
        if (d1!=0 or d2!=0 or d3!=0):
            print('no solution')
        elif (d1==0 and d2==0 and d3==0):
            print('infinite solution')
           
lhs = np.array([[1, 1, 1], [14, 19, 24], [13, 20, 36]])
rhs = np.array([183, 3727, 4784])

#lhs = np.array([[-4.0, -6.0, 5.0], [-2.0, 1.0, 6.0], [-5.0, 4.0, 3.0]])
#rhs = np.array([3.0, 31.0, 22.0])

print(rhs[0],rhs[1],rhs[2],lhs[0][1])
           
print(cramer(lhs,rhs))

183 3727 4784 1
45
44.99999999999997
[[183, 1, 1], [3727, 19, 24], [4784, 20, 36]]
[[1, 183, 1], [14, 3727, 24], [13, 4784, 36]]
[[1, 1, 183], [14, 19, 3727], [13, 20, 4784]]
1620
2745
3870
x:  36 y:  61 z:  86
None


In [30]:
import numpy as np
from numpy.linalg import linalg, inv

a = [[1,1,-2],[2,3,-2],[0,0,1]]

mat = np.array(a)
mat_inv = np.linalg.inv(mat)

print(mat_inv)

[[ 3. -1.  4.]
 [-2.  1. -2.]
 [ 0.  0.  1.]]
