In [41]:
import numpy as np
from numpy.linalg import linalg, inv
import sympy as sym
sym.init_printing()

a= ([1, 2, 3], [3, 4, 5], [6,7,8])

def mat_det(a):
    array = np.array(a)
    det = np.linalg.det(array)
    return det

print(mat_det(a))

a = [[1,2,3], [4,1,0], [0,0,1]]

def mat_inv(a):
    array = np.array(a)
    inv = np.linalg.inv(array)
    return inv

print(mat_inv(a))

def linr_eqn(lhs,rhs):
    l1 = np.array(lhs)
    r1 = np.array(rhs)
    var = np.linalg.solve(l1,r1)
    return var

#lhs = [[3, 4, 6], [2, 0, 5], [1, -8, 4]]
#rhs = [[45], [-20], [35]]


#lhs = [[1,2,-16],[3,-4,-14],[2,-10,5]]
#rhs = [[30],[-25],[-20]]

print(linr_eqn(lhs,rhs))

def mat_mul(a,b):
    mul = np.dot(a,b)
    return mul

print(mat_mul(lhs,rhs))

x,y,z = sym.symbols('x,y,z')

solns = sym.solve([
    1*x + 2*y - 16*z - 30, 
    3*x - 4*y - 14*z + 25,
    2*x - 10*y + 5*z + 20],
    [x, y, z])

print(f'{solns[x]}')
print(f'{solns[y]}')
print(f'{solns[z]}')



def cramer(lhs,rhs):
    d = round(np.linalg.det(lhs))
    print(d)
    m = [[lhs[0][0],lhs[0][1],lhs[0][2]],
         [lhs[1][0],lhs[1][1],lhs[1][2]],
         [lhs[2][0],lhs[2][1],lhs[2][2]]]
    print(np.linalg.det(m))
    
    m1 = [[rhs[0],lhs[0][1],lhs[0][2]],
          [rhs[1],lhs[1][1],lhs[1][2]],
          [rhs[2],lhs[2][1],lhs[2][2]]] 
    print(m1)
          
    m2 = [[lhs[0][0],rhs[0],lhs[0][2]],
          [lhs[1][0],rhs[1],lhs[1][2]],
          [lhs[2][0],rhs[2],lhs[2][2]]] 
    print(m2)
          
    m3 = [[lhs[0][0],lhs[0][1],rhs[0]],
          [lhs[1][0],lhs[1][1],rhs[1]],
          [lhs[2][0],lhs[2][1],rhs[2]]] 
    print(m3)

    d1 = round(np.linalg.det(m1))
    print(d1)
    d2 = round(np.linalg.det(m2))
    print(d2)
    d3 = round(np.linalg.det(m3))
    print(d3)
           
    if d!= 0:
           x = d1/d
           y = d2/d
           z = d3/d
           print('x: ',round(x),'y: ',round(y),'z: ',round(z))
    else:
        if (d1!=0 or d2!=0 or d3!=0):
            print('no solution')
        elif (d1==0 and d2==0 and d3==0):
            print('infinite solution')
           
lhs = np.array([[1.0, 2.0, 3.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
rhs = np.array([1.0, 2.0, 3.0])

#lhs = np.array([[-4.0, -6.0, 5.0], [-2.0, 1.0, 6.0], [-5.0, 4.0, 3.0]])
#rhs = np.array([3.0, 31.0, 22.0])

print(rhs[0],rhs[1],rhs[2],lhs[0][1])
           
print(cramer(lhs,rhs))
          

-3.7007434154172e-17
[[-0.14285714  0.28571429  0.42857143]
 [ 0.57142857 -0.14285714 -1.71428571]
 [ 0.          0.          1.        ]]
[-2.70215978e+16  5.40431955e+16 -2.70215978e+16]
[14 26 44]
-3355/53
-1535/106
-405/53
1.0 2.0 3.0 2.0
0
-3.7007434154172e-17
[[1.0, 2.0, 3.0], [2.0, 4.0, 5.0], [3.0, 7.0, 8.0]]
[[1.0, 1.0, 3.0], [3.0, 2.0, 5.0], [6.0, 3.0, 8.0]]
[[1.0, 2.0, 1.0], [3.0, 4.0, 2.0], [6.0, 7.0, 3.0]]
1
-2
1
no solution
None
